## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports split]					
set_property IOSTANDARD LVCMOS33 [get_ports split]
set_property PACKAGE_PIN W2 [get_ports bet_1]					
set_property IOSTANDARD LVCMOS33 [get_ports bet_1]
set_property PACKAGE_PIN U1 [get_ports bet_2]					
set_property IOSTANDARD LVCMOS33 [get_ports bet_2]
set_property PACKAGE_PIN T1 [get_ports bet_4]					
set_property IOSTANDARD LVCMOS33 [get_ports bet_4]
set_property PACKAGE_PIN R2 [get_ports bet_8]					
set_property IOSTANDARD LVCMOS33 [get_ports bet_8]

# LEDs
set_property PACKAGE_PIN U14 [get_ports LED_Draw]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_Draw]
set_property PACKAGE_PIN V14 [get_ports LED_Lose]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_Lose]
set_property PACKAGE_PIN V13 [get_ports LED_Win]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_Win]
set_property PACKAGE_PIN U16 [get_ports LED_split]
set_property IOSTANDARD LVCMOS33 [get_ports LED_split]

# 7-segment display
set_property PACKAGE_PIN W7 [get_ports LED_out[0]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[0]]
set_property PACKAGE_PIN W6 [get_ports LED_out[1]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[1]]
set_property PACKAGE_PIN U8 [get_ports LED_out[2]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[2]]
set_property PACKAGE_PIN V8 [get_ports LED_out[3]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[3]]
set_property PACKAGE_PIN U5 [get_ports LED_out[4]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[4]]
set_property PACKAGE_PIN V5 [get_ports LED_out[5]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[5]]
set_property PACKAGE_PIN U7 [get_ports LED_out[6]]					
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[6]]

set_property PACKAGE_PIN U2 [get_ports Anode_Activate[3]]					
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[3]]
set_property PACKAGE_PIN U4 [get_ports Anode_Activate[1]]					
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[1]]
set_property PACKAGE_PIN V4 [get_ports Anode_Activate[2]]					
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[2]]
set_property PACKAGE_PIN W4 [get_ports Anode_Activate[0]]					
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[0]]

# Buttons
set_property PACKAGE_PIN U18 [get_ports reset]						
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T18 [get_ports next]						
set_property IOSTANDARD LVCMOS33 [get_ports next]
set_property PACKAGE_PIN W19 [get_ports hit]						
set_property IOSTANDARD LVCMOS33 [get_ports hit]
set_property PACKAGE_PIN T17 [get_ports stand]						
set_property IOSTANDARD LVCMOS33 [get_ports stand]
set_property PACKAGE_PIN U17 [get_ports double]						
set_property IOSTANDARD LVCMOS33 [get_ports double]

# Additional outputs
set_property PACKAGE_PIN T9 [get_ports display12]
set_property IOSTANDARD LVCMOS33 [get_ports display12]
set_property PACKAGE_PIN T10 [get_ports display34]
set_property IOSTANDARD LVCMOS33 [get_ports display34]
